#Application properties
server:
  port: 8082

aws:
  services:
    bucket: ""

#AWS properties
cloud:
  aws:
    stack.auto: false
    region.static: "us-east-1"
    credentials:
      accessKey: ""
      secretKey: ""

